package org.openrdf.elmo.codegen;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;

import junit.framework.TestCase;

public class DeprecatedTest extends TestCase {
	
	/** Round Trip namespace. */
	private static final String TRIP = "http://example.org/roundtrip#";

	/** Directory used to store files generated by this test case. */
	private static File targetDir;

	public void testRoundTrip() throws Exception {
		File jar = createFile("trip.jar");
		OntologyConverter converter = createConventer();
		converter.addRdfSource(find("/ontologies/roundtrip-ontology.owl"));
		converter.bindPackageToNamespace("concepts.trip", TRIP);
		converter.init();
		converter.createClasses(jar);
		converter = createConventer();
		converter.addJar(jar.toURI().toURL());
		converter.bindPackageToNamespace("concepts.trip", TRIP);
		converter.init();
		File owl = createFile("roundtrip-ontology.owl");
		converter.createOntology(owl);
		String orig = read(find("/ontologies/roundtrip-ontology.owl")).trim();
		assertEquals(orig, read(owl.toURI().toURL()));
	}

	/**
	 * Setup the test case.
	 * 
	 * @throws Exception
	 */
	@Override
	protected void setUp() throws Exception {
		if (targetDir == null) {
			targetDir = File.createTempFile("elmo-codegen", "");
			targetDir.delete();
			targetDir = new File(targetDir.getParentFile(), "elmo-codegen");
			targetDir.mkdir();
		}
	}

	private OntologyConverter createConventer() {
		OntologyConverter converter = new OntologyConverter();
		converter.setImportJarOntologies(false);
		converter.addRdfSource(find("/ontologies/xsd-datatypes.rdf"));
		converter.addRdfSource(find("/ontologies/rdfs-schema.rdf"));
		converter.addRdfSource(find("/ontologies/owl-schema.rdf"));
		return converter;
	}

	/**
	 * Creates a new File object in the <code>targetDir</code> folder.
	 * 
	 * @param name
	 * @return
	 */
	private File createFile(String filename) {
		File file = new File(targetDir, filename);
		if (file.exists()) {
			file.delete();
		}
		return file;
	}

	/**
	 * Returns a resource from the classpath.
	 * 
	 * @param owl
	 * @return
	 */
	private URL find(String owl) {
		return getClass().getResource(owl);
	}

	private String read(URL url) throws IOException {
		InputStream in = url.openStream();
		int x= in.available();
		byte b[]= new byte[x];
		in.read(b);
		in.close();
		return new String(b);
	}
}
