#include "nsISupports.idl"

[scriptable, uuid(600859c4-7c38-11dc-8314-0800200c9a66)]
interface nsILifeCycle : nsISupports {
 boolean	isFailed();
 boolean 	isRunning();
 boolean 	isStarted();
 boolean 	isStarting();
 boolean 	isStopped();
 boolean 	isStopping();
 void 	start();
 void 	stop();
};
